MyCRM/MyCRM/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include('crmApp.urls', namespace='crm')),
    path('api/', include('api.urls', namespace='restapi')),
]

MyCRM/api/urls.py
from django.urls import path
from . import views
app_name = 'restapi'

urlpatterns = [
    path('subject/', views.SubjectListView.as_view(), name='subject_list'),
    path('subject/<pk>/',  views.SubjectDetailView.as_view(), name='subject_detail'),
    ]

MyCRM/crmApp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .models import Brands

app_name='crm'

urlpatterns=[
    path('accounts/newUser', views.userNew, name='new_user'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login',views.userLogin, name='login'),
    # path('logout',views.userLogout, name='logout'),
    path('brands/add', views.BrandAdd.as_view(), name='brand_add'),
    path('brands/delete/<slug:slug>', views.BrandDelete.as_view(), name='brand_del'),
    path('brands/update/<slug:slug>', views.BrandEdit.as_view(), name='brand_edit'),
    path('brands/<slug:slug>', views.BrandDetail.as_view(), name='brand_details'),
    path('brands/', views.BrandsView.as_view(model=Brands, context_object_name='brands', template_name='crmApp/brands/brands_list.html'), name='brand_list'),
    path('catalog/add', views.catalogModels_add, name='catalog_model_add'),
    path('catalog/delete/<slug:slug>', views.CataloModelDelete.as_view(), name='model_delete'),
    path('catalog/edit/<slug:slug>', views.catalogModelEdit, name='model_edit'),
    path('catalog/<slug:slug>', views.CatalogModelDetail.as_view(), name='model_details'),
    path('catalog/', views.CatalogView.as_view(), name='catalog_list'),
    path('store/add', views.store_add, name='store_add'),
    path('store/delete/<slug:slug>', views.store_delete, name='store_delete'),
    path('store/edit/<slug:slug>', views.StoreEdit.as_view(), name='store_edit'),
    path('store/<slug:slug>', views.StoreItem.as_view(), name='store_item'),
    path('store/', views.StoresList.as_view(), name='store_list'),
    path('suppliers/add', views.supplier_add, name='suppliers_add'),
    path('suppliers/<slug:slug>', views.supplier_details, name='suppliers_details'),
    path('suppliers/delete/<slug:slug>', views.SupplierDelete.as_view(), name='supplier_delete'),
    path('suppliers/edit/<slug:slug>', views.supplierEdit, name='supplier_edit'),
    path('suppliers/', views.supplier_list, name='suppliers_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('dashboard2/', views.dashboard2, name='dashboard2'),
    # path('dashboard/pressImportOrders/', views.pressButImportOrders, name='pressImportOrder'),
    path('product_list/', views.ProductsList.as_view(), name='products_list'),
    path('product_info_view/<int:id>', views.productInfoDetail, name='product_info'),
    # path('orders_list/', views.orderList, name='orders_list'),
    path('orders_list/', views.OrderList.as_view(), name='orders_list'),
    # path('order_info/createCdekOrder/<int:id>', views.createCdekOrder, name='create_cdek_order'),
    path('order_info/<int:id>', views.OrderInfoDetail, name='order_info'),
    # path('order_info/<int:id>', views.OrderInfoDetail.as_view(), name='order_info'),
    # path('load_avangard/', views.import_avangard,  name="import_avangard"),
    path('importmyown/', views.importMyOwn, name="import_myown"),
    path('importtraid/', views.importTradechas, name="import_trade"),
    path('syncinventory/', views.syncInventory, name="syncinventory"),
    path('syncinventoryresponce/<int:jobid>', views.getInventorySyncResults, name="getInventorySyncResults"),
    path('importavangardproducts/', views.impoRTAvangardProducts, name="avangardproducts"),
    path('celeryimportavangardproducts/', views.celery_handle_avangardstore, name="avangardproducts"),
]

MyCRM/crmApp/forms.py
from django import forms
from .models import Brands, Stores, Catalog
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .servicesCRM import DEPARTURE_CITIES


class BrandForm(forms.ModelForm):
    class Meta:
        model=Brands
        fields=['name', 'description', 'slug']

class SupplierForm(forms.Form):
    name=forms.CharField(max_length=20)
    slug=forms.SlugField()

class StoresForm(forms.ModelForm):
    class Meta:
        model=Stores
        fields=['catalog_item', 'quantity', 'wholesale_price', 'supplier']

class CatalogForm(forms.ModelForm):
    class Meta:
        model=Catalog
        fields=['article', 'brand_name', 'model_name', 'model_series']

class LoginForm(forms.Form):
    username=forms.CharField(max_length=11, widget=forms.TextInput(attrs={'autofocus':True}))
    password=forms.CharField(widget=forms.PasswordInput)


class UserRegForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name', 'last_name', 'email']


class OrderInfoForm(forms.Form):
    recieverFIO=forms.CharField(label='ФИО получателя', max_length=50)
    recieverPhone=forms.CharField(label='Номер телефона', max_length=11)
    phoneCountry=forms.CharField(label='Код страны', max_length=5)
    selectPVZ=forms.ChoiceField(label='ПВЗ СДЭК получателя')
    choices=list(map(lambda item: (item['id'], item['name']),DEPARTURE_CITIES))
    selectShippingFrom=forms.ChoiceField(label='Город отправки', widget=forms.RadioSelect,
                                         choices=choices, initial=(DEPARTURE_CITIES[0]['id'],DEPARTURE_CITIES[0]['name']))
    fromKazan = forms.ChoiceField(label='Тариф СДЭК из Чистополя')
    fromChelny = forms.ChoiceField(label='Тариф СДЭК из Н. Челнов')
    insurance=forms.IntegerField(label='Страховка груза (руб.)', required=False)

class OrderInfoFormNonPVZ(OrderInfoForm):
    selectPVZ=forms.ChoiceField(label='ПВЗ СДЭК получателя', required=False, widget=forms.Select(attrs={'disabled':'disabled'}))

class DashBoardForm(forms.Form):
    checkBoxOrders=forms.BooleanField(label='Импортировать заказы',
                                      required=False,
                                      widget=forms.CheckboxInput(attrs={'onclick':"id_depthDaysOrders.disabled=!this.checked"}))
    depthDaysOrders=forms.IntegerField(label='Глубина импорта заказов (дней)', required=False)
    checkBoxProducts=forms.BooleanField(label='Импортировать товары',
                                        required=False,
                                        widget=forms.CheckboxInput(attrs={'onclick':"id_depthDaysProducts.disabled=!this.checked"}))
    depthDaysProducts=forms.IntegerField(label='Глубина импорта товаров (дней)',
                                         widget=forms.NumberInput(attrs={'disabled':'disabled'}), required=False)
    checkBoxGroups=forms.BooleanField(label='Импортировать группы', required=False)
    checkBoxMyOwnProducts=forms.BooleanField(label='Импортировать мои товары', required=False)
    checkBoxAvangardProducts = forms.BooleanField(label='Импортировать из Авангарда', required=False)
    checkBoxSendToAli = forms.BooleanField(label='Отправить остатки в Али', required=False)
    checkBoxImportTradeChas = forms.BooleanField(label='Импортировать из Трейдчас', required=False)

# форма для загрузки файлов
class UploadFileForm(forms.Form):
    file = forms.FileField()

MyCRM/crmApp/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Brands, Catalog, Stores, Suppliers, AliOrdersProductList, AliProducts, AliOrders
from .forms import BrandForm, SupplierForm,\
    StoresForm, CatalogForm, LoginForm, UserRegForm, OrderInfoForm, OrderInfoFormNonPVZ, DashBoardForm, UploadFileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .servicesCRM import serviceAli, check_funcs, orderAliInfo, DEPARTURE_CITIES
from django.core.paginator import Paginator
from services.cdek_services import CdekAPI, CdekOrder
from services.utils import handle_myownstore, handle_tradechas, handle_syncInventory, handle_getsyncInventoryResults, handle_AvangardProducts
from crmApp.tasks import saveToFile
from crmApp.tasks import task_handle_avangardstore, task_handle_myownstore



# # пункты отправления посылок
# SOURCE_CITIES = {'selectTarifSaratov':'SAR4', 'selectTarifKazan':'KZN37',
#                  'selectTarifChelny': 'NCHL6'}
# сдэк
Account='0372b3fff5d6707cd1633469403952df'
Secure_password='afc14015cce5555ce582bf97b963d2d2'

# Create your views here.
class BrandsView(ListView):
    pass
    # model = Brands
    # context_object_name = 'brands'
    # template_name = 'crmApp/brands/brands_list.html'

class BrandDelete(DeleteView):
    model = Brands
    context_object_name = 'brand'
    template_name = 'brands/brands_delete.html'
    success_url = reverse_lazy('crm:brand_list')

class CatalogView(ListView):
    model=Catalog
    context_object_name = 'catalog_items'
    template_name = 'catalogModels/catalog_models_list.html'

class BrandDetail(DetailView):
    model=Brands
    context_object_name = 'brand'
    template_name='brands/brand_detail.html'

class CatalogModelDetail(DetailView):
    model = Catalog
    context_object_name = 'item'
    template_name = 'catalogModels/catalog_model.html'

class StoresList(ListView):
    model=Stores
    context_object_name = 'store'
    template_name = 'stores/store_list.html'

def store_add(request):
    if request.method=='POST':
        form = StoresForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crm:store_list')
    else:
        form=StoresForm()
        return render(request, 'stores/store_add.html', context={'form': form})

def store_delete(request, slug):
    item=Stores.objects.get(slug=slug)
    if request.method=='POST':
        item.delete()
        return redirect('crm:store_list')
    else:
        return render(request, 'stores/store_delete.html', context={'item':item})

class StoreItem(DetailView):
    model = Stores
    context_object_name = 'item'
    template_name = 'stores/store_details.html'

class BrandAdd(CreateView):
    form_class = BrandForm
    template_name = 'brands/brand_add.html'
    def form_valid(self, form):
        Brands.objects.create(**form.cleaned_data)
        return redirect('crm:brand_list')

def supplier_list(request):
    supp_list=Suppliers.objects.all()
    return render(request, 'suppliers/suppliers_list.html', context={'supp_list': supp_list})

def supplier_details(request, slug):
    supp_detail=Suppliers.objects.get(slug=slug)
    return render(request, 'suppliers/supplier_detail.html', context={'supp_detail': supp_detail})

def supplier_add(request):

    if request.method=='POST':
        form = SupplierForm(request.POST)
        if form.is_valid():
            Suppliers.objects.create(**form.cleaned_data)
            return redirect('crm:suppliers_list')
    else:
        form = SupplierForm()
        return render(request, 'suppliers/supplier_add.html', context={'form': form})

class SupplierDelete(DeleteView):
    model=Suppliers
    context_object_name = 'item'
    template_name = 'suppliers/supplier_delete.html'
    success_url = reverse_lazy('crm:suppliers_list')

class CataloModelDelete(DeleteView):
    model = Catalog
    context_object_name = 'item'
    template_name = 'catalogModels/catalog_model_delete.html'
    success_url = reverse_lazy('crm:catalog_list')

def catalogModels_add(request):

    if request.method=='POST':
        form = CatalogForm(request.POST)
        if form.is_valid():
            new_obj=form.save()
            return redirect(new_obj)
    else:
        form = CatalogForm()
        return render(request, 'catalogModels/catalog_model_add.html', context={'form': form})

class BrandEdit(UpdateView):
    model = Brands
    context_object_name = 'brand'
    template_name = 'crmApp/brands/brand_edit.html'
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:brand_list')

def supplierEdit(request, slug):
    obj=Suppliers.objects.get(slug=slug)
    if request.method=='POST':
        form=SupplierForm(request.POST)
        if form.is_valid():
            obj.name=form.cleaned_data['name']
            obj.slug=form.cleaned_data['slug']
            newobj=obj.save()
            return redirect('crm:suppliers_list')
    else:
        form = SupplierForm({'name': obj.name, 'slug': obj.slug})
        return render(request, 'suppliers/supplier_edit.html', context={'form': form})

def catalogModelEdit(request, slug):
    obj=Catalog.objects.get(slug=slug)
    if request.method=='POST':
        form=CatalogForm(request.POST, instance=obj)
        if form.is_valid():
            update_obj=form.save()
            return redirect(update_obj)

    else:
        form=CatalogForm(instance=obj)
        return render(request, 'catalogModels/catalog_model_edit.html', context={'form': form})

class StoreEdit(UpdateView):
    model = Stores
    context_object_name = 'item'
    template_name = 'crmApp/stores/stores_edit.html'
    fields = ['catalog_item', 'quantity', 'wholesale_price', 'supplier', 'slug']
    success_url = reverse_lazy('crm:store_list')


# def userLogin(request):
#     if request.method=='POST':
#         form=LoginForm(request.POST)
#         if form.is_valid():
#             username=form.cleaned_data['username']
#             psw=form.cleaned_data['password']
#             user=authenticate(request, username=username, password=psw)
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     url=request.GET.get('next','')
#                     return redirect(settings.LOGIN_REDIRECT_URL if url=='' else url)
#                 else:
#                     return HttpResponse('Юзер не активен')
#             else:
#                 return HttpResponse('Облом')
#         else: return HttpResponse(form.errors)
#     else:
#         form=LoginForm()
#         return render(request, 'registration/login.html', context={'form':form})
#
# def userLogout(request):
#     logout(request)
#     return HttpResponse('разлогинился')


@login_required
def dashboard(request):

    if request.method=='GET':
        form=DashBoardForm(initial={'depthDaysOrders':1, 'depthDaysProducts':3})

    else:
        form=DashBoardForm(request.POST)
        if form.is_valid():
            a = serviceAli()
            if form.cleaned_data['checkBoxOrders']:
                a.updateOrderList(int(form.data['depthDaysOrders']))
            if form.cleaned_data['checkBoxProducts']:
                a.updateProducts(int(form.data['depthDaysProducts']))
            if form.cleaned_data['checkBoxGroups']:
                a.updateGroupList()
            if form.cleaned_data['checkBoxMyOwnProducts']:
                handle_myownstore()
            if form.cleaned_data['checkBoxImportTradeChas']:
                handle_tradechas()
            if form.cleaned_data['checkBoxAvangardProducts']:
                handle_AvangardProducts()
            if form.cleaned_data['checkBoxSendToAli']:
                    handle_syncInventory()


    return render(request,'dashboard/dashboard.html', context={'form':form, 'active_page':'dashboard'})

def userNew(request):
    if request.method=='POST':
        form=UserRegForm(request.POST)
        if form.is_valid():
            new_user=form.save()
            login(request, new_user)
            return render(request, 'registration/newUserDone.html')
    else:
        form=UserRegForm()
    return render(request, 'registration/newUser.html', context={'form':form})


class ProductsList(ListView):
    model=AliProducts
    context_object_name = 'productsList'
    template_name = 'products-list/products_list.html'
    paginate_by = 10
    paginate_orphans = 5
    ordering='-gmt_create'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_page'] = 'productlist'
        return context


def productInfoDetail(request, id):
    try:
        product_detail = AliProducts.objects.get(product_id=id) # краткая информация из пакетной функции из БД
        a=serviceAli()
        productDetailInfo=a.getProduct(id) # детальная информация из одиночной функции из API
        skulist=productDetailInfo['aeop_ae_product_s_k_us']['global_aeop_ae_product_sku']
        return render(request, context={'product_info': product_detail, 'product_detail_info': productDetailInfo, 'skulist':skulist},
                      template_name='products-list/product_info.html')

    except Exception as err:
        print(f' ошибка: {err}')
        return redirect('crm:products_list')

class OrderList(ListView):
    model=AliOrders
    # context_object_name = 'orderList'
    template_name = 'orders/orders_list.html'
    ordering='-gmt_create'
    paginate_orphans=5
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_page'] = 'orderlist'
        return context


@check_funcs
def OrderInfoDetail(request, id):

MyCRM/crmApp/templates/crmApp/orders/order_info.html
{% extends 'crmApp/base.html' %}

{% block title %}Заказ {{ order_info.order_id }}{% endblock %}

{% block content %}
    <div class="order-info">
        <div class="order-info__title">
            Заказ: {{ order_info.order_id }}
        </div>
        <div class="blocks-row order-info__vert-style">
            <div class="block order-info__block">
                <div class="block__title">
                    Данные заказа неизменяемые
                </div>
                <div class="block__elem">
                 <span class="block_bold">Статус заказа:</span> {{ order_info.alidetailinfo_order_status }}
                </div>
                <div class="block__elem">
                    <span class="block_bold">Время создания заказа:</span> {{ order_info.alidetailinfo_gmt_create|date:"d M Y H:i" }}
                </div>
                <div class="block__elem">
                 <span class="block_bold">Адрес в Али:</span> {{ order_info.alidetailinfo_receipt_address }}
                </div>
                <div class="block__elem">
                 <span class="block_bold">Нормализованный адрес:</span> {{ order_info.pochta_full_normalized_address }}
                </div>
                <div class="block__elem"> <span class="block_bold">Товары:</span>
                    <ol>
                        {% for i in order_info.aliordersproductlist_product_name %}
                        <li>{{i}}</li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
            <form class="block order-info__block"  action="" method="post">
                {% csrf_token %}
                <div class="block__title">
                    Данные заказа изменяемые
                </div>
                <div class="block__elem">
                 <span class="block_bold">{{ form.recieverFIO.label }}:</span> {{ form.recieverFIO }}
                </div>
                <div class="block__elem">
                 <span class="block_bold">{{ form.phoneCountry.label }}</span> {{ form.phoneCountry }}
                </div>
                <div class="block__elem">
                 <span class="block_bold">{{ form.recieverPhone.label }}</span> {{ form.recieverPhone }}
                </div>
            {%  if  order_info.cdekorderresponse_cdekResponse.requests.0.state %}
                <div class="block__elem">
                    <span class="block_bold">Ответ СДЭК на новую заявку:</span> {{ order_info.cdekorderresponse_cdekResponse.requests.0.state }}
                </div>
                <div class="block__elem">
                    <span class="block_bold">Накладная СДЭК создана:</span> {{ order_info.cdekorderstatus_cdekStatus.requests.0.state }}
                </div>
                {% if order_info.cdekorderstatus_cdekStatus.requests.0.errors %}
                    <div class="block__elem">
                        <span class="block_bold">Ошибки создания накладной СДЭК:</span> {{ order_info.cdekorderstatus_cdekStatus.requests.0.errors }}
                    </div>
                {% endif %}
                <div class="block__elem">
                    <span class="block_bold">Номер накладной СДЭК:</span> {{ order_info.cdekorderstatus_cdekStatus.entity.cdek_number }}
                </div>
                <div class="block__elem">
                    <span class="block_bold">ПВЗ доставки:</span> {{ order_info.cdek_pvz.0.location.address }}
                </div>
            {% else %}
                <div class="block__radiobutton">
                    <span class="block_bold">Город отправки:</span> {{ form.selectShippingFrom }}
                </div>
                <div class="block__elem">
                    <span class="block_bold">Тариф:</span>
                        {{ form.fromKazan }}
                        {{ form.fromChelny }}
                </div>
                <div class="block__elem">
                    <span class="block_bold">{{ form.selectPVZ.label }}</span> {{ form.selectPVZ }}
                </div>
                <div class="block__elem">
                    <span class="block_bold">{{ form.insurance.label }}</span> {{ form.insurance }}
                </div>
                <input type="submit" value=" Создать СДЭК накладную"/>

            {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

MyCRM/crmApp/templates/crmApp/orders/orders_list.html
{% extends 'crmApp/base.html' %}
{% load static %}
{% block title %}List of orders{% endblock %}

{% block content %}
    <div class="main__title">панель заказов</div>
    <div class="block-list">
    {% for item in object_list  %}
    <a class="block-item" href='{% url "crm:order_info" id=item.order_id %}'>
        <header class="block-item__header">
            Номер: <span class="block-item_bold">{{ item.order_id }}</span > - Дата/время: <span class="block-item_bold">
            {{ item.gmt_create|date:"d.m.Y H:i:s e" }}</span>
        </header>
        <div class="block-item__list">
            Состав: <span class="block-item_bold">{{ item.products_list_names }}</span>
        </div>
        <footer class="block-item__data">
            Статус: <span class="block-item_bold">{{ item.order_status }}</span>
            Платеж: <span class="block-item_bold">{{ item.fund_status }}</span>
        </footer>
    </a>
    {% endfor %}
    </div>
        <div class="paginator">
            <span class="paginator__page-links">
                {% if page_obj.has_previous %}
                    <a href="{%  url 'crm:orders_list' %}?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}
            </span>
                <span class="paginator__page-current">
                    Страница: {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                <span class="paginator__page-links">
                {% if page_obj.has_next %}
                    <a href="{%  url 'crm:orders_list' %}?page={{ page_obj.next_page_number }}">следующая</a>
                {% endif %}
                </span>

        </div>
{% endblock %}